name: $(Date:yyyyMMdd).$(Rev:r)
resources:
  repositories:
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release
trigger: none
extends:
  template: azure-pipelines/1ES.Official.Publish.yml@MicroBuildTemplate
  parameters:
    pool:
      os: linux
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Ubuntu-2004
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    stages:
    - stage: PublishToMaven
      jobs:
      - job: PublishToMaven
        displayName: Maven Release job
        templateContext:
          type: releaseJob
          isProduction: true
        steps:
        - task: DownloadBuildArtifacts@1
          displayName: 'Download Jar Artifacts'
          inputs:
            buildType: specific
            project: 'a4d27ce2-a42d-4b71-8eef-78cee9a9728e'
            pipeline: 16486
            downloadType: specific
            extractTars: false
            itemPattern: 'm2/**'
        - script: |
            echo "import public key"
            echo $GPG_PUBLIC_B64 | base64 -d | gpg --import

            echo "import secret key"
            echo $GPG_SECRET_B64 | base64 -d | gpg --batch --passphrase $GPGPASS --import
          displayName: 'import GPG keys'
          env:
            GPG_PUBLIC_B64: $(GPG_PUBLIC_B64)
            GPG_SECRET_B64: $(GPG_SECRET_B64)
            GPGPASS: $(GPGPASS)
        - task: NodeTool@0
          displayName: 'Use Node 20.x'
          inputs:
            versionSpec: 20.x
        - script: |
            cd $(System.ArtifactsDirectory)/m2
            pluginJarFile=$(basename -- java-debug-parent/*.pom)

            # remove .* from end
            noExt=${pluginJarFile%.*}

            # remove *- from start
            export releaseVersion=${noExt##*-} 
            echo $releaseVersion

            export artifactFolder=$(pwd .)
            wget https://raw.githubusercontent.com/microsoft/java-debug/master/scripts/publishMaven.js

            export GPG_TTY=$(tty)
            node publishMaven.js -task gpg
          displayName: 'sign artifacts'
          env:
            GPG_PUBLIC_B64: $(GPG_PUBLIC_B64)
            GPG_SECRET_B64: $(GPG_SECRET_B64)
            GPGPASS: $(GPGPASS)
            NEXUS_OSSRHPASS: $(NEXUS_OSSRHPASS)
            NEXUS_OSSRHUSER: $(NEXUS_OSSRHUSER)
            NEXUS_STAGINGPROFILEID: $(NEXUS_STAGINGPROFILEID)
        - template: MicroBuild.Publish.yml@MicroBuildTemplate
          parameters: 
            intent: 'PackageDistribution'
            contentType: 'Maven'
            contentSource: 'Folder'
            folderLocation: '$(System.ArtifactsDirectory)/m2/java-debug-parent'
            waitForReleaseCompletion: true
            owners: 'jinbwan@microsoft.com'
            approvers: 'roml@microsoft.com'
        - template: MicroBuild.Publish.yml@MicroBuildTemplate
          parameters: 
            intent: 'PackageDistribution'
            contentType: 'Maven'
            contentSource: 'Folder'
            folderLocation: '$(System.ArtifactsDirectory)/m2/com.microsoft.java.debug.core'
            waitForReleaseCompletion: true
            owners: 'jinbwan@microsoft.com'
            approvers: 'roml@microsoft.com'
        - template: MicroBuild.Publish.yml@MicroBuildTemplate
          parameters: 
            intent: 'PackageDistribution'
            contentType: 'Maven'
            contentSource: 'Folder'
            folderLocation: '$(System.ArtifactsDirectory)/m2/com.microsoft.java.debug.plugin'
            waitForReleaseCompletion: true
            owners: 'jinbwan@microsoft.com'
            approvers: 'roml@microsoft.com'